on: [push]

jobs:
  # This workflow contains a single job called/with ID "deploy-preview"
  deploy-preview:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # The environment this job references
    environment:
      name: Preview
      url: ${{ steps.step_name.outputs.url_output }} # optional
    steps:
      - name: Deploy
        run: echo ok
