on: [push]

jobs:
  # This workflow contains a single job called/with ID "deploy-preview"
  deploy-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # The environment this job references
    environment:
      name: Dev
      url: htttp:://example.com/${{ github.ref }} # optional
    steps:
      - name: Deploy
        run: echo ok
